package com.ironhack.medicineproject.enums;

public enum GlobalStatus {

    NAME_TOO_SHORT,
    NAME_TOO_LONG,

    DOCTOR_ALREADY_EXISTS,
    DOCTOR_NOT_FOUND,

    MEDICINE_ALREADY_EXISTS,
    MEDICINE_NOT_FOUND,

    PATIENT_ALREADY_EXISTS,
    PATIENT_NOT_FOUND,

    PRESCRIPTION_ALREADY_EXISTS,
    PRESCRIPTION_NOT_FOUND,

    WRONG_USERNAME,
    WRONG_PASSWORD,

    DOCTOR_CREATED,
    PATIENT_CREATED,
    MEDICINE_CREATED,
    PRESCRIPTION_CREATED,

    DOCTOR_DELETED,
    PATIENT_DELETED,
    MEDICINE_DELETED,
    PRESCRIPTION_DELETED,

    PRESCRIPTION_CAN_NOT_BE_EMPTY

}
