package com.IronHack.Medicine.Project.security;

public enum globalStatus {

    NAME_TOO_SHORT,
    NAME_TOO_LONG,
    DOCTOR_ALREADY_EXISTS,
    DOCTOR_NOT_FOUND,
    MEDICINE_ALREADY_EXISTS,
    MEDICINE_NOT_FOUND,
    PATIENT_ALREADY_EXISTS,
    PATIENT_NOT_FOUND,
    WRONG_USERNAME,
    WRONG_PASSWORD,
    DOCTOR_CREATED,
    PATIENT_CREATED,
    MEDICINE_CREATED

}
